import Head from "next/head";
import Link from "next/link";
import styles from "../styles/About.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.link}>
          <Link href="/">Hi jjjjjjjjjjjjjjjjjjjjjjjj</Link>
        </div>
      </main>
    </div>
  );
}
