import Head from "next/head";
import Link from "next/link";

export default function About() {
  return (
    <div>
      <Head>
        <title>Create Next App abotu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>HI 2</h1>
        <Link href="/" className={styles.link}>
          link to home
        </Link>
      </main>
    </div>
  );
}
