import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={`${styles.link} ${styles.container}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Link href="/about">Hi aaaaaaaaaaaaaaaaaaaa</Link>
        <Image src="/img/a.png" alt="L" width="100px" height="150px" />
      </main>
    </div>
  );
}
